### PR TITLE
Include the IoU metric for select shapes across all clustering reducers

### PR DESCRIPTION
**Pull request by CKrawczyk**
This PR adds the intersection of union metric to be used with DBSCAN and four shapes
- rectangle
- rotateRectangle
- circle
- ellipse
- triangle

The reducer config yaml for this metric looks similar to:

```yaml
reducer_config:
    shape_reducer_dbscan:
        metric_type: IoU
        shape: rectangle
        eps: 0.5
        min_samples: 2
```

Basic unit tests are in place and this should be able to run on real data.

To Do:
- [x] Extend to all PFE shapes that are closed (no polygon as it does not have an extractor)
- [x] Extend to HDBSCAN as well
- [x] Test on real data
- [x] Do "assert close" checks in reducer unit test to prevent rounding errors

### CODE REVIEW

**Comment by CKrawczyk** [comment]
Updated this branch to also add a new reducer called `shape_reducer_optics`.  This is identical to the DBSCAN reducer but uses OPTICS instead.  All tests and docs have been updated.

**Comment by CKrawczyk** [comment]
Updated HDBSCAN reducer to be able to use the IoU metric.

**Comment by CKrawczyk** [comment]
Created a "how clustering works" python notebook and included it in the docs.

**Review by ramanakumars — CHANGES_REQUESTED** [review]
This looks really great! I have two minor observations: 
* The coverage has reduced slightly in the `shape_reducer_hdbscan.py` code. It's missing the check for the `metric_type` keyword (~line 86). May I suggest adding a similar test for HDBSCAN in `test_shape_reducer_dbscan_optics.py` to fix this?
* I'm seeing a ~3-4x increase in processing time for euclidean vs IoU. I haven't delved too deeply into what's causing it but I'm guessing it's the IoU_metric itself, and possibly the repeated calls to create the geometry. Is there any way to speed this up, or is it just something that we have to live with?

Lastly, I just want to say that the difference between the two metrics is night and day, in terms of the confidence in the final cluster! This is really cool!

**Comment by CKrawczyk** [comment]
Good catch on the missing test, I will get that together.  As for the speed, my guess is it is the Shapely geometry calculations that are slowing things down.  One of the reasons a Euclidian metric is used is it is extremely fast to compute and allows for several shortcuts to be taken along the way, once you move to any other metric (or at least one that is not vectorized easily) things will slow down.

As we are only ever clustering small numbers of classifications typically I don't think it is a big concern right now.  Might be worth doing some profiling in the future to see where exactly the bottleneck is.

**Pull request merged**
