### PR TITLE
Start using packaging.version for version parsing

### PR DESCRIPTION
**Pull request by CKrawczyk**
The extractor should use `packaging.version` so min and max versions can be set more easily.

### CODE REVIEW

**Comment by CKrawczyk** [comment]
Will address #286 

Some thought needs to go into the flag names for this.  The cases are:

- Set to the specific version number only
- Set only a major version (and grab all minor versions)
- Set a min version number only
- Set a max version number only
- Set a min and max version number

For clarity, both the min and max should be inclusive.

**Comment by CKrawczyk** [comment]
More tests and bug fixing have been done.  Just need to write new tests for `extract_csv.py` to bring the coverage back up and ensure the code works as expected.

**Comment by CKrawczyk** [comment]
Rebase to current master.

**Comment by CKrawczyk** [comment]
Test coverage back to where it was before.  All that is left to do is update all the docs and examples to match the new API.

**Comment by CKrawczyk** [comment]
Documents have been updated.  This is now ready for review.

**Comment by CKrawczyk** [comment]
When releasing this needs a major version bump as the API for running command line scripts has now changed.

**Comment by camallen** [comment]
@CKrawczyk folks are asking on talk how to aggregate across versions https://www.zooniverse.org/talk/1322/2507924

I thought this would be a released feature already. Any timeline on this being released?

**Comment by CKrawczyk** [comment]
I am at a conference next week, but I plan to release it the week after that.

**Pull request merged**
