### PR TITLE
Increasing visibility of batch extraction and reduction functions

### PR DESCRIPTION
**Pull request by ramanakumars**
This PR is essentially to be able to create importable batch extraction and reduction functions which can work directly on `pandas.DataFrame` objects and return `pandas.DataFrame` objects. The existing CSV functionality is unaffected by this change.

### CODE REVIEW

**Comment by ramanakumars** [comment]
I think this PR is ready for v1 of the data exports! Currently the `batch_extract` and `batch_reduce` functions take in a pandas DataFrame object which is basically just the classification and extracts CSV file read in. Ultimately I think it would be nice if these functions took in a JSON list instead, so that we don't have to do the JSON parsing for the `annotations`, `metadata` and `data` keywords, but I think that can be a different PR.

**Comment by lcjohnso** [comment]
Hi @CKrawczyk -- This PR has been idle, but after discussion zoo-side I think it is ready to go! I've tagged you for review -- let us know if you have any questions.

**Review by CKrawczyk — APPROVED** [review]
Everything looks good to me.

Might be worth splitting the `batch_utils.py` file into `batch_utils.py`, `batch_extract.py`, and `batch_reduce.py` just from an organization perspective to keep files more "single purpose", but this is a non-blocker.

**Comment by lcjohnso** [comment]
@ramanakumars @CKrawczyk -- I plan to merge and deploy tomorrow unless I hear otherwise.  Thanks to you both for your effort on this PR!

**Pull request merged**
